server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://aa3ver34aikrmg.ckvo3luvnizp.sa-east-1.rds.amazonaws.com:3306/ebdb
    username: luisMattos
    password: teste1234Luis
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false